/-
Copyright (c) 2026 Stefan Kebekus. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Stefan Kebekus
-/
module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.RingTheory.Algebraic.Integral
public import VD.AlgebraicDependence.GermCharacteristic
public import VD.AlgebraicDependence.GrowthClass
public import VD.AlgebraicDependence.PolynomialCharacteristic

/-!
# Growth Fields and Algebraic Dependence — Algebraic Dependence work packages F2–F5

See `VD/AlgebraicDependence/PLAN-AlgebraicDependence.md`, §8.

Mathlib target: follows the germ field `VD/Field/` upstream. Dependencies: packages D and F1.

Planned content:

- F2: the **growth field** `MeromorphicOn.GermRing.growthField hG : IntermediateField ℂ
  (germRing ℂ univ)` of germs whose characteristic lies in a growth class `G` (the structure
  `IsGrowthClass l G` and its instances `isGrowthClass_isBigO`, `isGrowthClass_isLittleO`
  live in `VD/AlgebraicDependence/GrowthClass.lean`, package D); the classical field of small
  functions `S(f)` as the little-o instance along `volume.cofinite ⊓ atTop`.
- F3 = T6, `mem_growthField_of_isAlgebraic`: **growth fields are relatively algebraically
  closed** in the field of meromorphic germs.
- F4 = T7, `ValueDistribution.exists_characteristic_le_of_isAlgebraic_adjoin`: if `f` is
  algebraic over the field generated by `g₁, …, gₙ`, then
  `T(r, f) ≤ C · (Σᵢ T(r, gᵢ) + 1)` eventually.
- F5, `exists_abs_characteristic_aeval_sub_le`: the polynomial Valiron–Mohon'ko identity for
  `P ∈ F[X]`, `F` a growth field.
-/
