/-
Copyright (c) 2026 Stefan Kebekus. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Stefan Kebekus
-/
module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.RingTheory.Algebraic.Integral
public import VD.AlgebraicDependence.GermCharacteristic
public import VD.AlgebraicDependence.GrowthClass
public import VD.AlgebraicDependence.PolynomialCharacteristic

/-!
# Growth Fields and Algebraic Dependence — Algebraic Dependence work packages F2–F5

See `VD/AlgebraicDependence/PLAN-AlgebraicDependence.md`, §8.

Mathlib target: follows the germ field `VD/Field/` upstream. Dependencies: packages D and F1.

Throughout, `K := MeromorphicOn.germRing ℂ Set.univ` is the field of meromorphic germs on `ℂ`,
`characteristic : K → ℝ → ℝ` is the Nevanlinna characteristic of a germ, and
`IsGrowthClass l G` is a growth class (`VD/AlgebraicDependence/GrowthClass.lean`).

## Main definitions and results

- F2, `MeromorphicOn.GermRing.growthField hG : IntermediateField ℂ K`: the **growth field** of
  germs whose characteristic lies in the growth class `G`; `smallFunctions`, the classical
  field `S(f)` of functions small with respect to `f`, as the little-o instance.
- F3 = T6, `MeromorphicOn.GermRing.mem_growthField_of_isAlgebraic`: **growth fields are
  relatively algebraically closed** in the field of meromorphic germs.
- F4 = T7, `ValueDistribution.exists_characteristic_le_of_isAlgebraic_adjoin`: if `f` is
  algebraic over the field generated by `g₁, …, gₙ`, then
  `T(r, f) ≤ C · (Σᵢ T(r, gᵢ) + 1)` eventually.
- F5, `MeromorphicOn.GermRing.characteristic_aeval_le` and
  `exists_abs_characteristic_aeval_sub_le`: the polynomial Valiron–Mohon'ko identity
  `T(r, P(a)) = deg P · T(r, a) + u(r)`, `u ∈ G`, for `P ∈ F[X]`, `F` a growth field.
-/

@[expose] public section

open Asymptotics Filter Finset Function Polynomial Real Set Topology

namespace MeromorphicOn.GermRing

variable {l : Filter ℝ} {G : (ℝ → ℝ) → Prop}

/-!
## Growth Fields
-/

/-- The **growth field** of a growth class `G`: the meromorphic germs on `ℂ` whose
characteristic lies in `G`. It is an intermediate field between the constants and the field of
all meromorphic germs. -/
def growthField (hG : IsGrowthClass l G) : IntermediateField ℂ (germRing ℂ univ) where
  carrier := {a | G (characteristic a)}
  add_mem' {a b} ha hb := by
    refine hG.of_le (v := characteristic a + characteristic b + fun _ ↦ log 2)
      (hG.add (hG.add ha hb) (hG.const _)) ?_ ?_
    · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
      exact characteristic_nonneg _ hr
    · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
      exact characteristic_add_le a b hr
  mul_mem' {a b} ha hb := by
    refine hG.of_le (v := characteristic a + characteristic b) (hG.add ha hb) ?_ ?_
    · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
      exact characteristic_nonneg _ hr
    · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
      exact characteristic_mul_le a b hr
  algebraMap_mem' c := by
    refine hG.of_le (v := fun _ ↦ log⁺ ‖c‖) (hG.const _) ?_ ?_
    · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
      exact characteristic_nonneg _ hr
    · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
      exact (characteristic_algebraMap c (zero_lt_one.trans_le hr).ne').le
  inv_mem' a ha := by
    obtain ⟨c, hc⟩ := exists_abs_characteristic_inv_sub_le a
    refine hG.of_le (v := characteristic a + fun _ ↦ c) (hG.add ha (hG.const _)) ?_ ?_
    · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
      exact characteristic_nonneg _ hr
    · filter_upwards with r
      change characteristic a⁻¹ r ≤ characteristic a r + c
      linarith [(abs_le.1 (hc r)).2]

theorem mem_growthField_iff (hG : IsGrowthClass l G) {a : germRing ℂ univ} :
    a ∈ growthField hG ↔ G (characteristic a) := Iff.rfl

/-- The classical field `S(f)` of **small functions** with respect to a germ `f` whose
characteristic tends to infinity along `l`: the germs `a` with `T(r, a) = o(T(r, f))`. -/
noncomputable abbrev smallFunctions (hl : l ≤ atTop) {f : germRing ℂ univ}
    (hf : Tendsto (characteristic f) l atTop) : IntermediateField ℂ (germRing ℂ univ) :=
  growthField (isGrowthClass_isLittleO hl hf)

/-!
## Relative Algebraic Closedness
-/

/-- **Growth fields are relatively algebraically closed** (T6): a meromorphic germ that is
algebraic over the growth field of `G` lies in the growth field. -/
theorem mem_growthField_of_isAlgebraic (hG : IsGrowthClass l G) {a : germRing ℂ univ}
    (ha : IsAlgebraic (growthField hG) a) : a ∈ growthField hG := by
  obtain ⟨p, hp, hpa⟩ := isAlgebraic_iff_isIntegral.1 ha
  -- The monic relation, as a relation in the field of germs.
  have hrel : a ^ p.natDegree
      + ∑ j ∈ range p.natDegree, (p.coeff j : germRing ℂ univ) * a ^ j = 0 := by
    have := congrArg (aeval a) hp.as_sum
    rw [← aeval_def, this] at hpa
    simpa using hpa
  refine hG.of_le (v := ∑ j ∈ range p.natDegree, characteristic (p.coeff j : germRing ℂ univ)
      + fun _ ↦ log (p.natDegree : ℝ))
    (hG.add (hG.sum fun j _ ↦ (p.coeff j).2) (hG.const _)) ?_ ?_
  · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
    exact characteristic_nonneg _ hr
  · filter_upwards [hG.le_atTop (eventually_ge_atTop 1)] with r hr
    simpa [Finset.sum_apply] using characteristic_le_sum_characteristic_of_monic_eq_zero hrel hr

/-!
## The Polynomial Valiron–Mohon'ko Identity for Germs
-/

/-- `aeval a P`, written as a polynomial expression in the chosen representatives. -/
theorem out_aeval_eventuallyEq (hG : IsGrowthClass l G) (a : germRing ℂ univ)
    (P : (growthField hG)[X]) :
    out (aeval a P) =ᶠ[codiscrete ℂ]
      ∑ j ∈ range (P.natDegree + 1), out (P.coeff j : germRing ℂ univ) * out a ^ j := by
  rw [aeval_eq_sum_range]
  simp only [Algebra.smul_def, IntermediateField.algebraMap_apply]
  exact (out_sum _ _).trans (EventuallyEq.finset_sum fun j _ ↦
    (out_mul _ _).trans ((EventuallyEq.refl _ _).mul (out_pow a j)))

/-- The upper bound of the polynomial Valiron–Mohon'ko identity for germs (D1 at germ level):
`T(r, P(a)) ≤ deg P · T(r, a) + Σ_{j ≤ deg P} T(r, coeff j) + log (deg P + 1)` for `1 ≤ r`. -/
theorem characteristic_aeval_le (hG : IsGrowthClass l G) (a : germRing ℂ univ)
    (P : (growthField hG)[X]) {r : ℝ} (hr : 1 ≤ r) :
    characteristic (aeval a P) r
      ≤ P.natDegree * characteristic a r
        + ∑ j ∈ range (P.natDegree + 1), characteristic (P.coeff j : germRing ℂ univ) r
        + log (P.natDegree + 1) := by
  rw [characteristic, ValueDistribution.characteristic_congr_codiscrete
    (out_aeval_eventuallyEq hG a P) (zero_lt_one.trans_le hr).ne']
  exact ValueDistribution.characteristic_polynomial_le (meromorphic_out a)
    (fun j ↦ meromorphic_out _) hr

/-- **The polynomial Valiron–Mohon'ko identity for germs** (F5): for a nonzero polynomial `P`
with coefficients in the growth field of `G`, `T(r, P(a)) = deg P · T(r, a) + u(r)` with
`u ∈ G`. -/
theorem exists_abs_characteristic_aeval_sub_le (hG : IsGrowthClass l G) (a : germRing ℂ univ)
    {P : (growthField hG)[X]} (hP : P ≠ 0) :
    ∃ u, G u ∧ ∀ᶠ r in l,
      |characteristic (aeval a P) r - P.natDegree * characteristic a r| ≤ u r := by
  -- The leading coefficient is not codiscretely zero.
  have hd : ¬ out (P.coeff P.natDegree : germRing ℂ univ) =ᶠ[codiscrete ℂ] 0 := by
    intro h
    have : (P.coeff P.natDegree : germRing ℂ univ) = 0 :=
      eq_zero_iff_out_eventuallyEq_zero.2 h
    exact hP (leadingCoeff_eq_zero.1 (ZeroMemClass.coe_eq_zero.1 this))
  obtain ⟨u, hu, hu'⟩ := ValueDistribution.exists_abs_characteristic_polynomial_sub_mem hG
    (meromorphic_out a) (fun j ↦ meromorphic_out (P.coeff j : germRing ℂ univ))
    (fun j _ ↦ (P.coeff j).2) hd
  refine ⟨u, hu, ?_⟩
  filter_upwards [hu', hG.le_atTop (eventually_ge_atTop 1)] with r hr hr₁
  rwa [characteristic, ValueDistribution.characteristic_congr_codiscrete
    (out_aeval_eventuallyEq hG a P) (zero_lt_one.trans_le hr₁).ne']

end MeromorphicOn.GermRing

/-!
## Algebraic over the Field Generated by Finitely Many Functions
-/

namespace ValueDistribution

open MeromorphicOn.GermRing

/-- **Algebraic dependence** (T7): if a meromorphic function `f` is algebraic over the field
generated by meromorphic functions `g i`, `i : ι` finite, then
`T(r, f) ≤ C · (Σᵢ T(r, g i) + 1)` for all large `r`. -/
theorem exists_characteristic_le_of_isAlgebraic_adjoin {ι : Type*} [Fintype ι] {g : ι → ℂ → ℂ}
    (hg : ∀ i, Meromorphic (g i)) {f : ℂ → ℂ} (hf : Meromorphic f)
    (h : IsAlgebraic (IntermediateField.adjoin ℂ (Set.range fun i ↦ toGerm (hg i)))
      (toGerm hf)) :
    ∃ C, ∀ᶠ r in atTop, characteristic f ⊤ r ≤ C * (∑ i, characteristic (g i) ⊤ r + 1) := by
  set φ : ℝ → ℝ := fun r ↦ ∑ i, characteristic (g i) ⊤ r + 1 with hφ_def
  have hφ₁ : ∀ᶠ r in atTop, 1 ≤ φ r := by
    filter_upwards [eventually_ge_atTop 1] with r hr
    simp only [hφ_def]
    linarith [sum_nonneg fun i (_ : i ∈ Finset.univ) ↦ characteristic_nonneg (f := g i) (a := ⊤) hr]
  have hφ : (1 : ℝ → ℝ) =O[atTop] φ := by
    refine IsBigO.of_bound 1 ?_
    filter_upwards [hφ₁] with r hr
    simpa [Real.norm_of_nonneg (zero_le_one.trans hr)] using hr
  have hG := isGrowthClass_isBigO le_rfl hφ
  -- The generators lie in the growth field of `O(φ)`.
  have hle : IntermediateField.adjoin ℂ (Set.range fun i ↦ toGerm (hg i)) ≤ growthField hG := by
    rw [IntermediateField.adjoin_le_iff]
    rintro _ ⟨i, rfl⟩
    refine IsBigO.of_bound 1 ?_
    filter_upwards [eventually_ge_atTop 1, hφ₁] with r hr hr'
    rw [characteristic_toGerm (hg i) (zero_lt_one.trans_le hr).ne', one_mul,
      Real.norm_of_nonneg (characteristic_nonneg hr), Real.norm_of_nonneg (zero_le_one.trans hr')]
    simp only [hφ_def]
    linarith [single_le_sum
      (fun j (_ : j ∈ Finset.univ) ↦ characteristic_nonneg (f := g j) (a := ⊤) hr) (mem_univ i)]
  -- Hence `f` is algebraic over the growth field, and lies in it.
  have h' : IsAlgebraic (growthField hG) (toGerm hf) := by
    let : Algebra (IntermediateField.adjoin ℂ (Set.range fun i ↦ toGerm (hg i)))
      (growthField hG) := (IntermediateField.inclusion hle).toAlgebra
    have : IsScalarTower (IntermediateField.adjoin ℂ (Set.range fun i ↦ toGerm (hg i)))
      (growthField hG) (MeromorphicOn.germRing ℂ univ) := .of_algebraMap_eq fun _ ↦ rfl
    exact h.extendScalars (IntermediateField.inclusion_injective hle)
  obtain ⟨C, hC⟩ := isBigO_iff.1 (mem_growthField_of_isAlgebraic hG h')
  refine ⟨C, ?_⟩
  filter_upwards [hC, eventually_ge_atTop 1, hφ₁] with r hr hr₁ hr'
  rwa [characteristic_toGerm hf (zero_lt_one.trans_le hr₁).ne',
    Real.norm_of_nonneg (characteristic_nonneg hr₁), Real.norm_of_nonneg (zero_le_one.trans hr')]
    at hr

end ValueDistribution
